export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const GET_POKEMON_CARD = 'GET_POKEMON_CARD';
export const SEARCH_POKEMON_INFO = 'SEARCH_POKEMON_INFO';
export const FILTER_POKEMON_LIST = 'FILTER_POKEMON_LIST';

export const ADD_AXIOS_STARTED = 'ADD_AXIOS_STARTED';
export const ADD_AXIOS_SUCCESS = 'ADD_AXIOS_SUCCESS';
export const ADD_AXIOS_FAILURE = 'ADD_AXIOS_FAILURE';
